server:
  port: 8082

spring:
  application:
    name: producer-service

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - prometheus

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka