receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  zipkin:
    endpoint: ${ZIPKIN_URL}/api/v2/spans
    tls:
      insecure: true
#  jaeger:
#    endpoint: ${JAEGER_COLLECTOR_URL}
#    tls:
#      insecure: true
  prometheus:
    endpoint: otel-collector:8889
  prometheusremotewrite:
    endpoint: ${PROMETHEUS_URL}/api/v1/push

service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - zipkin
#        - jaeger
    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - prometheus
        - prometheusremotewrite
#    logs:
#      receivers:
#        - otlp
#      processors:
#        - batch
#      exporters:
#        - logging
