server:
  port: 8761

spring:
  application:
    name: discovery-service

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - prometheus

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false